### ISSUE TITLE
Documentation for `idw` looks wrong

### ISSUE THREAD

**Issue by barryrowlingson** [ptarroso/phylin#1]
The help for `idw` says:
```
Arguments:

  values: A table of points to be interpolated. Table must contain x
          and y locations, and a column of values to be interpolated.
```

which makes it sound like `values` should have x, y, and value columns. But if you do that, you get an error:
```
Error in diag(values) : 'list' object cannot be coerced to type 'double'
```

Because in the code the only thing done with `values` is:

```
wx <- w %*% diag(values)
```

and in all the examples `values` is set to be only the vector of measured values at the locations.

The help for your `krig` function seems correct for `idw` - perhaps you changed something and didn't update the documentation for `idw`:

```
  values: A vector of values per sampled location.

  coords: A table containing longitude and latitude of sample locations
          for each value.

    grid: A table containing the coordinates of locations to
          interpolate
```

Found via a gis stackexchange question:

https://gis.stackexchange.com/questions/389566/error-in-performing-shepard-idw-in-r/389574#389574

**Comment by ptarroso** [comment]
@barryrowlingson Thanks for pointing that out! It is fixed here. I will upload it to CRAN in the next version update.
