### ISSUE TITLE
Shepards Modified idw

### ISSUE THREAD

**Issue by tra6sdc** [ptarroso/phylin#2]
Hello,

I have looked at the function provided to calculate the inverse distance weighting using Shepards Modified method, with a specified radius R. In the Wikipedia page for this approach (https://en.wikipedia.org/wiki/Inverse_distance_weighting), the weights are $$w(x) = \left(\frac{max(0,r-d(x, x_i))}{r.d(x, xi)}\right)^p$$, rather than $$w(x) = \left(\frac{r-d(x, x_i)}{r.d(x, xi)}\right)^p$$, ie the numerator is forced to be strictly non-negative. Do you know which is the correct application of Shepards Modification? Thanks.

**Comment by ptarroso** [comment]
Thanks for your feedback @tra6sdc 

Yes, you are correct. The implementation of the Modified Shepard formulae is not complete. As you say, it misses the max call and it might result on negative weights. This is not noticeable in the example given with the help and most likely with even powers. However, with odd powers can be tricky...  It can be corrected in line 13 of the idw function with `pmax(0, R-d.real)`
Thanks

**Comment by ptarroso** [comment]
check the released version here: 
https://github.com/ptarroso/phylin/releases/tag/2.0.3

I'll update CRAN version as possible.
